# Generated by Django 4.2.4 on 2023-08-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('downloaded', 'Downloaded')], default='drafted', max_length=20),
        ),
    ]
