# Generated by Django 4.2.4 on 2023-08-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writingapp', '0002_draft_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
